name: Cypress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci || npm i

      # roda Cypress headless (vai gerar ./allure-results por causa do plugin)
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          spec: "cypress-tests/e2e/**/*.cy.js"

      # gera relatório HTML do Allure
      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # publica os artefatos (pode baixar pelo UI do GitHub Actions)
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
