name: Cypress

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 2 * * *" # 02:00 UTC -> nightly FULL

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  smoke:
    name: "Smoke (tags: smoke) • CI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node 18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci || npm i

      # restaurar histórico p/ Allure Trend (se existir)
      - name: Restore Allure history
        run: |
          git fetch origin gh-pages:gh-pages || true
          mkdir -p allure-results/history
          if git show gh-pages:history >/dev/null 2>&1; then
            git show gh-pages:history > history.zip
            unzip -o history.zip -d allure-results || true
          fi

      - name: Run Cypress (smoke only)
        run: npx cypress run --env allure=true,grepTags=smoke

      - name: Generate Allure report
        run: npx allure-commandline generate allure-results --clean -o allure-report

      - name: Save Allure history
        run: |
          cp -r allure-report/history . || true
          # exporta history para reuso em próximos runs
          (cd allure-report && zip -r ../history.zip history >/dev/null) || true
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git checkout --orphan gh-pages-temp
          mkdir -p .
          mv history.zip history || true
          git add history || true
          git commit -m "chore: update allure history [ci skip]" || true
          git push -f origin gh-pages-temp:gh-pages || true

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  full:
    name: Full Suite (nightly)
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node 18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci || npm i

      - name: Run Cypress (full)
        run: npx cypress run --env allure=true

      - name: Generate Allure report
        run: npx allure-commandline generate allure-results --clean -o allure-report

      - name: Upload Allure (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-full
          path: allure-report
          retention-days: 7
