name: Cypress

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * *"   # Nightly às 03:00 UTC
  workflow_dispatch:

jobs:
  smoke:
    name: Smoke (tags=smoke)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 18.18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # evita erro do --loader que algumas libs transitivas injetam via NODE_OPTIONS
      - name: Clear NODE_OPTIONS (evita erro do --loader)
        run: echo "NODE_OPTIONS=" >> $GITHUB_ENV

      - name: Install deps
        run: npm ci

      - name: Show versions
        run: |
          node -v
          npm -v
          npx cypress --version

      - name: Run Cypress (smoke only)
        run: npx cypress run --env allure=true,grepTags=smoke

      - name: Generate Allure
        run: |
          npm run allure:generate
          touch allure-report/.nojekyll

      - name: Upload allure artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy-pages:
    name: Deploy Allure to GitHub Pages
    needs: smoke
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download allure artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

  full:
    name: Full Suite (nightly)
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 18.18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Clear NODE_OPTIONS (evita erro do --loader)
        run: echo "NODE_OPTIONS=" >> $GITHUB_ENV

      - name: Install deps
        run: npm ci

      - name: Run Cypress (full suite)
        run: npx cypress run --env allure=true

      - name: Generate Allure
        run: |
          npm run allure:generate
          touch allure-report/.nojekyll

      - name: Upload allure artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
