name: Cypress

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # 03:00 UTC diariamente (ajuste se quiser)
    - cron: '0 3 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  smoke:
    if: ${{ github.event_name != 'schedule' }}
    name: Smoke (tags=smoke)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 18.18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci || npm i

      - name: Run Cypress (smoke only)
        env:
          CYPRESS_VIDEO: "false"
        run: |
          npx cypress run --env allure=true,grepTags=smoke

      - name: Generate Allure report
        run: |
          npx allure-commandline generate allure-results --clean -o allure-report

      - name: Upload allure artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          if-no-files-found: error

  deploy-pages:
    name: Deploy Allure to GitHub Pages
    needs: smoke
    if: ${{ needs.smoke.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download allure artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4

  full:
    name: Full Suite (nightly)
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node 18.18 + cache
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci || npm i

      - name: Run Cypress (full)
        env:
          CYPRESS_VIDEO: "false"
        run: |
          # roda a suíte completa (sem grep)
          npx cypress run --env allure=true

      - name: Generate Allure report (nightly)
        run: |
          npx allure-commandline generate allure-results --clean -o allure-report
